### ISSUE TITLE
Support more than one BaseURL

### ISSUE THREAD

**Issue by DiXaM96** [rouanw/build-window#15]
It would be nice to support more than one BaseURL e.g. more than one Jenkins instance which is grouped in Dashboard.

**Comment by rouanw** [comment]
That's a great idea, thanks @DiXaM96!

I've just pushed a commit to enable this behaviour for Jenkins. Will you please give it a test and if all's good I'll add it for the other CI servers too.

Change your config to look something like:

```json
{
  "builds": [
    {"id": "Lucene-Solr-Maven-master", "server": "Jenkins", "baseUrl": "https://builds.apache.org"}
  ]
}

```

**Comment by DiXaM96** [comment]
Wow you're fast!
I tested it, looks good:
![grafik](https://user-images.githubusercontent.com/22687967/80567870-386f4d80-89f6-11ea-8e4f-5ce2dad9eb13.png)

But after starting smashing I get this error in console (not sure if this was happen yesterday):
```bash
/home/users/d/work/repo/devops/build-dashboard/jobs/build_health.rb:119: warning: URI.escape is obsolete
{ 5780 rufus-scheduler intercepted an error:
  5780   job:
  5780     Rufus::Scheduler::EveryJob "15s" {}
  5780   error:
  5780     5780
  5780     SNMP::RequestTimeout
  5780     host do-jenkins01.pvt.de not responding
  5780       /home/users/d/.gem/gems/snmp-1.3.2/lib/snmp/manager.rb:283:in `get_next'
  5780       /home/users/d/.gem/gems/snmp-1.3.2/lib/snmp/manager.rb:443:in `block in walk'
  5780       /home/users/d/.gem/gems/snmp-1.3.2/lib/snmp/manager.rb:442:in `loop'
  5780       /home/users/d/.gem/gems/snmp-1.3.2/lib/snmp/manager.rb:442:in `walk'
  5780       /home/users/d/work/repo/devops/build-dashboard/jobs/snmp.rb:15:in `block in get_snmp'
  5780       /home/users/d/.gem/gems/snmp-1.3.2/lib/snmp/manager.rb:222:in `open'
  5780       /home/users/d/work/repo/devops/build-dashboard/jobs/snmp.rb:14:in `get_snmp'
  5780       /home/users/d/work/repo/devops/build-dashboard/jobs/snmp.rb:27:in `block in <top (required)>'
  5780       /home/users/d/.gem/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:210:in `do_call'
  5780       /home/users/d/.gem/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:254:in `trigger_now'
  5780       /home/users/d/.gem/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:296:in `block (3 levels) in start_work_thread'
  5780       /home/users/d/.gem/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:299:in `block (2 levels) in start_work_thread'
  5780       /home/users/d/.gem/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:285:in `loop'
  5780       /home/users/d/.gem/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:285:in `block in start_work_thread'
  5780   tz:
  5780     ENV['TZ']: 
  5780     Time.now: 2020-04-29 08:48:54 +0200
  5780     local_tzone: #<TZInfo::DataTimezone: Europe/Zurich>
  5780   et-orbi:
  5780     (etz:nil,tnz:"CEST",tziv:"2.0.2",tzidv:nil,rv:"2.7.1",rp:"x86_64-linux",win:false,rorv:nil,astz:nil,eov:"1.2.4",eotnz:#<TZInfo::DataTimezone: Europe/Zurich>,eotnfz:"+0200",eotlzn:"Europe/Zurich",eotnfZ:"CEST",debian:"Europe/Zurich",centos:nil,osx:"Europe/Zurich")
  5780   scheduler:
  5780     object_id: 4380
  5780     opts:
  5780       {}
  5780       frequency: 0.3
  5780       scheduler_lock: #<Rufus::Scheduler::NullLock:0x0000563543a871d0>
  5780       trigger_lock: #<Rufus::Scheduler::NullLock:0x0000563543a871a8>
  5780     uptime: 366.2898681163788 (6m6s289)
  5780     down?: false
  5780     threads: 3
  5780       thread: #<Thread:0x0000563543a8e5c0 /home/users/d/.gem/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler.rb:546 sleep>
  5780       thread_key: rufus_scheduler_4380
  5780       work_threads: 2
  5780         active: 1
  5780         vacant: 1
  5780         max_work_threads: 28
  5780       mutexes: {}
  5780     jobs: 2
  5780       at_jobs: 0
  5780       in_jobs: 0
  5780       every_jobs: 2
  5780       interval_jobs: 0
  5780       cron_jobs: 0
  5780     running_jobs: 1
  5780     work_queue: 0
} 5780 .
```

**Comment by rouanw** [comment]
@DiXaM96 the error looks like you're getting a timeout from your jenkins server. Maybe see if you can reach it in your web browser or using `curl` from your terminal? If you want the exact URL BuildWindow is trying to get, you can debug or `puts` this variable: https://github.com/rouanw/build-window/blob/4eddb9aeec6b38f877755e253cea1c42833d0277/jobs/build_health.rb#L113.

**Comment by DiXaM96** [comment]
was because a wrong configured timezone, thanks.

**Comment by DiXaM96** [comment]
Do you think it is possible to group different CI-Servers/URLs in the dashboard e.g. with swimlanes?

**Comment by rouanw** [comment]
No, that functionality isn't currently supported. We could add it, but it wouldn't be straightforward:

- grouping builds by CI server or `baseUrl` wouldn't work because some folks would need their grouping done differently - e.g. by team, business area or build type. (An alternative would be to allow users to specify a `groupId` in their configuration and use that for grouping.)
- if I remember correctly, the Smashing UI does its own best-effort arranging of widgets, so we'd probably have to do some odd things to tell it to arrange them differently.

If you can think of a simple way of implementing visual grouping I'd be happy to discuss your approach and accept a pull request.

**Comment by DiXaM96** [comment]
cool, thanks for now!
