### ISSUE TITLE
get_jenkins_build_health crashes when Job build history is empty

### ISSUE THREAD

**Issue by hpaluch-pil** [rouanw/build-window#18]
Hi!

While testing this project on my Jenkins I had found that when any of watched jobs has empty build history (was never build yet, or that history was deleted) then the background job will crash with this stacktrace:
```
{ 47389702653540 rufus-scheduler intercepted an error:
  47389702653540   job:
  47389702653540     Rufus::Scheduler::EveryJob "20s" {}
  47389702653540   error:
  47389702653540     47389702653540
  47389702653540     NoMethodError
  47389702653540     undefined method `[]' for nil:NilClass
  47389702653540       /home/smashing/projects/build-window/jobs/build_health.rb:126:in `get_jenkins_build_health'
  47389702653540       /home/smashing/projects/build-window/jobs/build_health.rb:10:in `block in api_functions'
  47389702653540       /home/smashing/projects/build-window/jobs/build_health.rb:36:in `get_build_health'
  47389702653540       /home/smashing/projects/build-window/jobs/build_health.rb:137:in `block (2 levels) in <top (required)>'
  47389702653540       /home/smashing/projects/build-window/jobs/build_health.rb:136:in `each'
  47389702653540       /home/smashing/projects/build-window/jobs/build_health.rb:136:in `block in <top (required)>'
  47389702653540       /home/smashing/projects/build-window/vendor/bundle/ruby/2.5.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:223:in `do_call'
  47389702653540       /home/smashing/projects/build-window/vendor/bundle/ruby/2.5.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:267:in `trigger_now'
  47389702653540       /home/smashing/projects/build-window/vendor/bundle/ruby/2.5.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:312:in `block (3 levels) in start_work_thread'
  47389702653540       /home/smashing/projects/build-window/vendor/bundle/ruby/2.5.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:315:in `block (2 levels) in start_work_thread'
  47389702653540       /home/smashing/projects/build-window/vendor/bundle/ruby/2.5.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:301:in `loop'
  47389702653540       /home/smashing/projects/build-window/vendor/bundle/ruby/2.5.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:301:in `block in start_work_thread'
  47389702653540   tz:
  47389702653540     ENV['TZ']:
  47389702653540     Time.now: 2020-09-17 07:35:35 +0000
  47389702653540     local_tzone: #<TZInfo::DataTimezone: Etc/UTC>
  47389702653540   et-orbi:
  47389702653540     (etz:nil,tnz:"UTC",tziv:"2.0.2",tzidv:nil,rv:"2.5.5",rp:"x86_64-linux-gnu",win:false,rorv:nil,astz:nil,eov:"1.2.4",eotnz:#<TZInfo::DataTimezone: Etc/UTC>,eotnfz:"+0000",eotlzn:"Etc/UTC",eotnfZ:"UTC",debian:"Etc/UTC",centos:nil,osx:"Etc/UTC")
  47389702653540   scheduler:
  47389702653540     object_id: 47389697385120
  47389702653540     opts:
  47389702653540       {}
  47389702653540       frequency: 0.3
  47389702653540       scheduler_lock: #<Rufus::Scheduler::NullLock:0x000056338c284270>
  47389702653540       trigger_lock: #<Rufus::Scheduler::NullLock:0x000056338c284248>
  47389702653540     uptime: 240.1780390739441 (4m0.178069353s)
  47389702653540     down?: false
  47389702653540     threads: 2
  47389702653540       thread: #<Thread:0x000056338c273128@/home/smashing/projects/build-window/vendor/bundle/ruby/2.5.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler.rb:545 sleep>
  47389702653540       thread_key: rufus_scheduler_47389697385120
  47389702653540       work_threads: 1
  47389702653540         active: 1
  47389702653540         vacant: 0
  47389702653540         max_work_threads: 28
  47389702653540       mutexes: {}
  47389702653540     jobs: 1
  47389702653540       at_jobs: 0
  47389702653540       in_jobs: 0
  47389702653540       every_jobs: 1
  47389702653540       interval_jobs: 0
  47389702653540       cron_jobs: 0
  47389702653540     running_jobs: 1
  47389702653540     work_queue: 0
} 47389702653540 .
```

The problem is caused by fact that Jenkins returns empty result array in such case:
```json
{"_class":"hudson.model.FreeStyleProject","builds":[]}
```

Here is place where that crash occurs:
```ruby
  latest_build = builds_with_status.first
  return {
    name: latest_build['fullDisplayName'],   #line 126
    # ...
  }
```
So the problem is - what should be returned when there is no build history for job (`latest_build` is `nil`).

**Comment by rouanw** [comment]
Thanks for raising the issue @hpaluch-pil! I took a quick look and this is likely also an issue for the other CI serrvers.

I don't think the background job will crash, though. Smashing's scheduler should be smart enough to log the error and move on and so you'll see something (admittedly unattractive) like this on the dashboard until there are builds:

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/2362668/95573270-7bb0fc00-0a2b-11eb-9150-fde5e857cc27.png">

**Comment by rouanw** [comment]
Marking this as `wontfix` for now due to time constraints but always open to pull requests.
