### ISSUE TITLE
Dashing start fails when teamCityBaseUrl is not defined on builds.json

### ISSUE THREAD

**Issue by stefanteixeira** [rouanw/build-window#5]
Hi,

I'm trying to use your project on a Docker container, then I noticed that the following section in ```config.ru```

```ruby
require 'teamcity'
TeamCity.configure do |config|
  config.endpoint = Builds::BUILD_CONFIG['teamCityBaseUrl'] + '/app/rest?guest=1'
end
```

is causing this error:

```
config.ru:23:in `block (2 levels) in <main>': undefined method `+' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/teamcity-ruby-client-1.3.1/lib/teamcity/configuration.rb:33:in `configure'
	from config.ru:22:in `block in <main>'
	from /usr/local/bundle/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/bundle/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /usr/local/bundle/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
	from /usr/local/bundle/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
	from /usr/local/bundle/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /usr/local/bundle/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
	from /usr/local/bundle/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
	from /usr/local/bundle/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
	from /usr/local/bundle/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
	from /usr/local/bundle/bin/thin:16:in `load'
	from /usr/local/bundle/bin/thin:16:in `<main>'
```

when 'teamCityBaseUrl' is not defined on builds.json (I'm using it with GoCD only).

**Comment by rouanw** [comment]
Thanks for spotting this @stefanteixeira. I've resolved the issue. Please let me know if it doesn't work.

**Comment by herotest** [comment]
If Jenkins has to be authenticated, where should the AUTH details be mentioned?

**Comment by rouanw** [comment]
@herotest you need to have the `JENKINS_USER` and `JENKINS_TOKEN` environment variables set. You can place these (one per line) in a `.env` file at the root of the project or set them on the terminal when running `dashing start`.
